package com.mumukiller.alert.recognition.pattern;

/**
 * Created by Mumukiller on 23.06.2017.
 */
public enum PatternType {
    KICKING_BULL,
    KICKING_BEAR,

    BREAKAWAY_BULL,
    BREAKAWAY_BEAR,

    THREE_LINE_STRIKE_BULL,
    THREE_LINE_STRIKE_BEAR,

    UPSIDE_TASUKI_GAP,
    DOWNSIDE_TASUKI_GAP,

    UPSIDE_GAP_THREE_METHODS,
    DOWNSIDE_GAP_THREE_METHODS,

    BELT_HOLD_BULL,
    BELT_HOLD_BEAR,

    CONCEALING_BABY_SWALLOW,
    UNIQUE_THREE_RIVER_BOTTOM,
    IDENTICAL_THREE_CROWS,

    //TODO[MM] Need to implement
    BEARISH_ON_NECK_LINE,
    IN_NECK_LINE,
    THRUSTING_LINE,

    THREE_START_BEAR,
    THREE_START_BULL,

    THREE_INSIDE_UP,
    THREE_INSIDE_DOWN,

    THREE_OUTSIDE_UP,
    THREE_OUTSIDE_DOWN,

    THREE_WHITE_SOLDIERS,
    THREE_BLACK_CROWS,

    HANGING_MAN,
    SHOOTING_STAR,

    DELIBERATION,
    THREE_STAR_IN_THE_SOUTH,

    BEARISH_UPSIDE_GAP_TWO_CROWS,
    TWO_CROWS,

    EVENING_DOJI_STAR,
    MORNING_DOJI_STAR,

    EVENING_STAR,
    MORNING_STAR,

    ABANDON_BABY_BULLISH,
    ABANDON_BABY_BEARISH,

    HOMING_PIGEON,
    MATCHING_LOW,

    MEETING_LINES_BEARISH,
    MEETING_LINES_BULLISH,

    PIERCING_PATTERN,
    DARK_CLOUD_COVER,

    DOJI_STAR_BULLISH,
    DOJI_STAR_BEARISH,

    HARAMI_BULLISH,
    HARAMI_BEARISH,

    HARAMI_CROSS_BULLISH,
    HARAMI_CROSS_BEARISH,

    ENGULFING_BULLISH,
    ENGULFING_BEARISH,

    UNKNOWN;
}
